/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.Panel.*;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.*;
import com.formdev.flatlaf.FlatIntelliJLaf;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    public SideMenu sideMenu;
    public JPanel Content = new JPanel();
    public CardLayout cardLayout;
    public Home home;
    public SanPham sanPham;
    public PhieuNhap phieuNhap;
    public PhieuXuat phieuXuat;
    public KhachHang khachHang;
    public NhanVien nhanVien;
    public PhanQuyen phanQuyen;
    public ThongKe thongKe;
    private Color MainColor = new Color(255, 255, 255);

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        home = new Home();
        sanPham = new SanPham();
        phieuNhap = new PhieuNhap();
        phieuXuat = new PhieuXuat();
        khachHang = new KhachHang();
        nhanVien = new NhanVien();
        phanQuyen = new PhanQuyen();
        thongKe = new ThongKe();
        
        this.setTitle("Cua Hang Dien Thoai");
        this.setSize(new Dimension(1280, 720));
        this.setLayout(new BorderLayout(0, 0));
        
        sideMenu = new SideMenu(this);
        getContentPane().add(sideMenu, BorderLayout.WEST);
        
//        Content = new JPanel();
        Content.setSize(new Dimension(1030, 720));
        Content.setBackground(MainColor);
        Content.setLayout(new CardLayout(0, 0));
        cardLayout = (CardLayout) Content.getLayout();
        Content.add(home, "home");
        Content.add(sanPham, "sanPham");
        Content.add(phieuNhap, "phieuNhap");
        Content.add(phieuXuat, "phieuXuat");
        Content.add(khachHang, "khachHang");
        Content.add(nhanVien, "nhanVien");
        Content.add(phanQuyen, "phanQuyen");
        Content.add(thongKe, "thongKe");

        getContentPane().add(Content, BorderLayout.CENTER);

        this.setLocationRelativeTo(null);
    }
    
    public void switchCard(String panelName) {
        cardLayout.show(Content, panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UIManager.setLookAndFeel(new FlatIntelliJLaf());

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
