/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Dialog;

import BUS.PhienBanSanPhamBUS;
import BUS.SanPhamBUS;
import DTO.PhienBanSanPhamDTO;
import DTO.SanPhamDTO;
import helper.Formatter;
import helper.Validator;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ChonSanPhamDialog extends javax.swing.JDialog {

    public SanPhamBUS spBUS = new SanPhamBUS();
    public ArrayList<SanPhamDTO> spList = new ArrayList<>();
    private PhienBanSanPhamBUS pbspBUS = new PhienBanSanPhamBUS();
    private ArrayList<PhienBanSanPhamDTO> pbspList;
    private DefaultTableModel tblSPModel;
    private DefaultTableModel tblPBSPModel;
    public int selectedId;
    private String mode;
    
    public ChonSanPhamDialog(java.awt.Frame parent, boolean modal, ArrayList<SanPhamDTO> spList, ArrayList<PhienBanSanPhamDTO> pbspList, String mode) {
        super(parent, modal);
        this.mode = mode;
        if(mode.equals("nhap")) {
            this.spList = spBUS.getAll();
            this.pbspList = pbspBUS.getAll();
        }
        if(mode.equals("xuat")) {
            this.spList = spList;
            this.pbspList = pbspList;
        }
        initComponents();
        initComponentsCustom();
    }

    public void initComponentsCustom() {
        this.setLocationRelativeTo(null);
        setTitle("Chọn sản phẩm");
        tblSPModel = (DefaultTableModel) spTable.getModel();
        tblPBSPModel = (DefaultTableModel) pbspTable.getModel();
        loadSPToTable();
        chonSPBtn.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent e) {
                try {
                    pbspTable.getValueAt(pbspTable.getSelectedRow(), 0);
                    dispose();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Chưa chọn phiên bản");
                }
            }
        });
    }
    
    public void loadSPToTable() {
        for(SanPhamDTO i : this.spList) {
            tblSPModel.addRow(new Object[]{
                i.getId(),
                i.getTen()
            });
        }
    }
    
    public int getSelectedId() {
        try {
            return (int) pbspTable.getValueAt(pbspTable.getSelectedRow(), 0);
        }
        catch (Exception e){
            return -1;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        spTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pbspTable = new javax.swing.JTable();
        chonSPBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        spTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        spTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        spTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                spTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(spTable);
        if (spTable.getColumnModel().getColumnCount() > 0) {
            spTable.getColumnModel().getColumn(0).setResizable(false);
            spTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            spTable.getColumnModel().getColumn(1).setResizable(false);
            spTable.getColumnModel().getColumn(1).setPreferredWidth(210);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Chọn sản phẩm");

        pbspTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "RAM", "ROM", "Màu", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pbspTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        pbspTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(pbspTable);
        if (pbspTable.getColumnModel().getColumnCount() > 0) {
            pbspTable.getColumnModel().getColumn(0).setResizable(false);
            pbspTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            pbspTable.getColumnModel().getColumn(1).setResizable(false);
            pbspTable.getColumnModel().getColumn(2).setResizable(false);
            pbspTable.getColumnModel().getColumn(3).setResizable(false);
            pbspTable.getColumnModel().getColumn(4).setResizable(false);
        }

        chonSPBtn.setBackground(new java.awt.Color(102, 204, 255));
        chonSPBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chonSPBtn.setForeground(new java.awt.Color(255, 255, 255));
        chonSPBtn.setText("Chọn sản phẩm này");
        chonSPBtn.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(chonSPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(chonSPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spTableMousePressed
        tblPBSPModel.setRowCount(0);
        int row = spTable.getSelectedRow();
        int id = (int) spTable.getValueAt(row, 0);
        for(PhienBanSanPhamDTO i : this.pbspList) {
            if(i.getIdSanPham() == id) {
                if(mode.equals("xuat"))
                    if(i.getSoLuong() > 0) {
                        tblPBSPModel.addRow(new Object[]{
                            i.getId(),
                            i.getRam(),
                            i.getRom(),
                            i.getMau(),
                            i.getSoLuong(),
                        });
                    }
                if(mode.equals("nhap")) {
                    tblPBSPModel.addRow(new Object[]{
                        i.getId(),
                        i.getRam(),
                        i.getRom(),
                        i.getMau(),
                        i.getSoLuong(),
                    });
                }
            }
        }
    }//GEN-LAST:event_spTableMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton chonSPBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable pbspTable;
    private javax.swing.JTable spTable;
    // End of variables declaration//GEN-END:variables
}
