/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Panel;

import BUS.NhaCungCapBUS;
import BUS.NhanVienBUS;
import BUS.PhieuNhapBUS;
import DTO.PhieuNhapDTO;
import GUI.Component.SearchBar;
import GUI.Component.ToolBarButton;
import GUI.Dialog.PhieuNhapDialog;
import GUI.Main;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import helper.Formatter;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class PhieuNhap extends javax.swing.JPanel implements ActionListener{

    public PhieuNhapBUS pnBUS = new PhieuNhapBUS();
    public NhaCungCapBUS nccBUS = new NhaCungCapBUS();
    public NhanVienBUS nvBUS = new NhanVienBUS();
    public ArrayList<PhieuNhapDTO> phieuNhapList = pnBUS.getAll();
    private Main main;
    
    private DefaultTableModel tableModel;
    public SearchBar searchBar;
    ToolBarButton chiTietBtn = new ToolBarButton("Chi tiết", "toolBar_detail.svg", "detail");
    ToolBarButton themBtn = new ToolBarButton("Thêm", "toolBar_add.svg", "add");
    ToolBarButton xoaBtn = new ToolBarButton("Xóa", "toolBar_delete.svg", "delete");
    
    /**
     * Creates new form PhieuNhap
     */
    public PhieuNhap(Main main) {
        initComponents();
        initComponentsCustom();
        this.main = main;
        loadDataToTable(this.phieuNhapList);
    }
    
    public void initComponentsCustom() {
        searchBar = new SearchBar(new String[]{"Tất cả", "Mã", "Tên", "Giới tính", "Số điện thoại", "Email", "Chức vụ"});
        searchBar.txtSearch.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent e) {
//                searchEvent();
            }
        });
        searchBar.lamMoiBtn.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent e) {
//                reloadEvent();
            }
        });
        searchBar.cbxType.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
//                searchEvent();
            }
        });
        topPanel.add(searchBar, BorderLayout.CENTER);
        toolBar.add(chiTietBtn);
        toolBar.add(themBtn);
        toolBar.add(xoaBtn);
        chiTietBtn.addActionListener(this);
        themBtn.addActionListener(this);
        xoaBtn.addActionListener(this);
        pnTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tableModel = (DefaultTableModel) pnTable.getModel();
    }
    
    public void loadDataToTable(ArrayList<PhieuNhapDTO> pnList) {
        tableModel.setRowCount(0);
        for(PhieuNhapDTO i : pnList){
            tableModel.addRow(new Object[] {
                i.getId(), 
                nccBUS.getNameByID(i.getIdNhaCungCap()), 
                nvBUS.getNameByID(i.getIdNhanVien()), 
                Formatter.FormatDateTime(i.getNgayNhap()), 
                Formatter.FormatVND(i.getTongTien())});
        }
    }
    
    public void searchEvent() {
        
    }
    
    public void reloadEvent() {                                       
        searchBar.txtSearch.setText("");
        loadDataToTable(phieuNhapList);
    }
    
    public int getSelectedRow() {
        int index = pnTable.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(main, "Bạn chưa chọn phiếu nhập nào", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        return index;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        toolBar = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1030, 720));
        setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(221, 221, 221)));
        topPanel.setPreferredSize(new java.awt.Dimension(1030, 100));
        topPanel.setLayout(new java.awt.BorderLayout());

        toolBar.setBackground(new java.awt.Color(255, 255, 255));
        toolBar.setRollover(true);
        toolBar.setPreferredSize(new java.awt.Dimension(400, 100));
        topPanel.add(toolBar, java.awt.BorderLayout.LINE_END);

        add(topPanel, java.awt.BorderLayout.PAGE_START);

        pnTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Nhà cung cấp", "Nhân viên nhập", "Ngày nhập", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pnTable.setFocusable(false);
        pnTable.setRowHeight(32);
        pnTable.setSelectionBackground(new java.awt.Color(190, 215, 220));
        pnTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        pnTable.setShowGrid(true);
        pnTable.getTableHeader().setResizingAllowed(false);
        pnTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(pnTable);
        if (pnTable.getColumnModel().getColumnCount() > 0) {
            pnTable.getColumnModel().getColumn(0).setResizable(false);
            pnTable.getColumnModel().getColumn(1).setResizable(false);
            pnTable.getColumnModel().getColumn(2).setResizable(false);
            pnTable.getColumnModel().getColumn(3).setResizable(false);
            pnTable.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pnTable;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() == chiTietBtn) {            
            int index = getSelectedRow();
            if(index != -1) {
                PhieuNhapDialog pnDialog = new PhieuNhapDialog(main, true, this, phieuNhapList.get(index), "detail");
                pnDialog.setVisible(true);
                loadDataToTable(phieuNhapList);
            }
        }
    }

}
