/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Panel;

import GUI.Component.SideMenuItem;
import GUI.Main;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Admin
 */
public class SideMenu extends javax.swing.JPanel {

    Main main;
    String[][] menuSt = {
        {"Trang chủ", "home", "sideMenu_home.svg"},
        {"Sản phẩm", "sanPham", "sideMenu_sanPham.svg"},
        {"Phiếu nhập", "phieuNhap", "sideMenu_phieuNhap.svg"},
        {"Hóa đơn", "hoaDon", "sideMenu_hoaDon.svg"},
        {"Khách hàng", "khachHang", "sideMenu_khachHang.svg"},
        {"Nhân viên", "nhanVien", "sideMenu_nhanVien.svg"},
        {"Nhà cung cấp", "nhaCungCap", "sideMenu_nhaCungCap.svg"},
        {"Phân quyền", "phanQuyen", "sideMenu_phanQuyen.svg"},
        {"Thống kê", "thongKe", "sideMenu_thongKe.svg"}
    };
    public SideMenuItem menuItems[];
    Color itemBgColor = new Color(255, 255, 255);
    Color itemFontColor = new Color(0, 0, 0);
    Color selectedItemBgColor = new Color(190, 215, 220);
    Color selectedItemFontColor = new Color(0, 0, 0);
    
    /**
     * Creates new form MenuBar
     */
    public SideMenu() {
        initComponents();
    }

    public SideMenu(Main main) {
        initComponents();
        this.main = main;
        menuItems = new SideMenuItem[menuSt.length];
        for(int i=0; i<menuSt.length; i++) {
            menuItems[i] = new SideMenuItem(main, menuSt[i][0], menuSt[i][1], menuSt[i][2]);
            menuItems[i].addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent evt) {
                    selectingMenuItem(evt);
                }
            });
            centerPanel.add(menuItems[i]);
        }
        menuItems[0].isSelected = true;
        menuItems[0].setBackground(selectedItemBgColor);
        menuItems[0].text.setForeground(selectedItemFontColor);
    }
    
    public void selectingMenuItem(MouseEvent evt) {
        for (int i = 0; i < menuSt.length; i++) {
            if (evt.getSource() == menuItems[i]) {
                menuItems[i].isSelected = true;
                menuItems[i].setBackground(selectedItemBgColor);
                menuItems[i].text.setForeground(selectedItemFontColor);
            } else {
                menuItems[i].isSelected = false;
                menuItems[i].setBackground(itemBgColor);
                menuItems[i].text.setForeground(itemFontColor);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        userIcon = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        userRole = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(250, 720));
        setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        topPanel.setPreferredSize(new java.awt.Dimension(250, 70));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/sideMenu_user.png"))); // NOI18N

        userName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userName.setText("Tên nhân viên");

        userRole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userRole.setText("Chức vụ");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userName)
                    .addComponent(userRole))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(userRole)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(topPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        add(centerPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(bottomPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userRole;
    // End of variables declaration//GEN-END:variables
}
